apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "colour.fullname" . }}
  labels:
    {{- include "colour.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "colour.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "colour.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: colour
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          {{- if .Values.namespaceEnv }}
          env:
            - name: NAMESPACE
              value: {{ .Values.namespaceEnv | quote }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
