name: k8s-validate

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: k8s-validate-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
      - run: helm lint kubernetes/chart
      - run: helm template colour kubernetes/chart

  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Install kubeconform
        run: |
          curl -sSL https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xz kubeconform
          sudo mv kubeconform /usr/local/bin/
      - run: kubeconform -strict kubernetes/blue/*.yaml kubernetes/green/*.yaml
